#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          tvprobe
# Required-Start:    $remote_fs $syslog $mysql
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the tvprobe server
# Description:       Controls the tvprobe server watchdog
### END INIT INFO


# tvprobe daemon
# chkconfig: 345 20 80
# description: tvprobe daemon
# processname:tvprobe 

DAEMON_PATH="/home/pi/IPTV-Analyzer/nodejs/"

DAEMON=forever
DAEMONOPTS="tvprobe.js"

NAME=tvprobe
DESC="webserver tvprobe"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
        printf "%-50s" "Starting $NAME..."
        cd $DAEMON_PATH
        PID=`$DAEMON -c "node" $DAEMONOPTS > /dev/null 2>&1 & echo $!`
        #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z $PID ]; then
                printf "%s\n"  "Service not running"
            elif [ -z "`ps axf | grep $PID | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            $DAEMON stop $DAEMONOPTS
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
        $0 stop
        $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
